### ISSUE TITLE
Please support cells spanning multiple rows or/and columns in https://lwebapp.com/en/html-table-to-ascii

### ISSUE THREAD

**Issue by jpluimers** [openHacking/lwebapp-comment#2]
I like https://lwebapp.com/en/html-table-to-ascii a lot.

(Note: all examples below are for "Header location=`None`")

One improvement would be for it to support HTML-tables like this one:

``` html
<table>
<tbody>
  <tr>
    <td rowspan="2"></td>
    <td colspan="3"></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</tbody>
</table>
```

The current output for `Unicode` is this:

``` text
╔══╗
║  ║
║  ║
╚══╝
```

and for `ASCII (separated)` is this:

``` text
+--+
|  |
+--+
|  |
+--+
```

When filling the cells with values like this HTML:

``` html
<table>
<tbody>
  <tr>
    <td rowspan="2">a</td>
    <td colspan="3">a</td>
  </tr>
  <tr>
    <td>a</td>
    <td>a</td>
    <td>a</td>
  </tr>
</tbody>
</table>
```

Then both the `Unicode` and `ASCII (separated)` generated text becomes this:

``` text
Invalid array length
```

It would be nice if that changed to the below output (in addition without any cell content it should remove the `a` entries).

Proposte output for `Unicode` is this:

``` text
╔═══╦═══════════╗
║ a ║ a         ║
║   ╠═══╦═══╦═══╣
║   ║ a ║ a ║ a ║
╚═══╩═══╩═══╩═══╝
```

and for `ASCII (separated)` is this:

``` text
+---+-----------+
| a | a         |
|   +---+---+---+
|   | a | a | a |
+---+---+---+---+
```

Thanks for considering this issue.

--jeroen

**Comment by openHacking** [comment]
Thank you for your attention. I'll be working on this and I'll let you know when I'm done.

**Comment by openHacking** [comment]
I have updated a new tool to be compatible with tables with merged cells. It can only be converted to Unicode format for the time being. I will continue to update in the future.

You are welcome to try this tool, the address is here

https://lwebapp.com/en/table-to-ascii
